# SpendDNA - Financial Transaction Analysis

**Name:** Prithika S J

**Course:** Data Analytics & Data Science


**Objective**

Build a fintech-style transaction analytics system that cleans raw transaction data, extracts vendors, categorizes spending, detects anomalies, identifies spending archetypes, and generates an insightful financial report using Python, Pandas, and NumPy.

In [16]:
# AI-assisted: Library import and project setup

import pandas as pd
import numpy as np
from datetime import datetime

In [17]:
# AI-assisted: Loading dataset

df = pd.read_csv("Data set for DADS June.csv")

print("Dataset Loaded Successfully!")
print()

print("Shape:", df.shape)
print()

df.head()

Dataset Loaded Successfully!

Shape: (1328, 8)

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
0,2024-01-01,03:11,AMAZON SELLER SVCS,Debit,₹2462,678275.0,UPI,TXN190872
1,01-Jan-24,05:44,BHIM-BMTC,DR,50.00,681007.0,UPI,TXN143064
2,01-Jan-24,09:35,NEFT-TECHCRUSH LABS-SALARY MAY24,CR,₹84728,484728.0,NEFT,TXN246316
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,Debit,₹1828,-748745.0,UPI,TXN569226
4,01 Jan 2024,14:23,BHIM-BLINKIT,Debit,270.00,680737.0,UPI,TXN968962

In [18]:
print("="*60)
print("DATASET INFORMATION")
print("="*60)

print("\nColumns")
print(df.columns.tolist())

print("\nData Types")
print(df.dtypes)

print("\nMissing Values")
print(df.isnull().sum())

print("\nDuplicate Rows")
print(df.duplicated().sum())

============================================================
DATASET INFORMATION
============================================================

Columns
['Date', 'Time', 'Description', 'Type', 'Amount', 'Balance', 'Mode', 'Ref']

Data Types
Date            object
Time            object
Description     object
Type            object
Amount          object
Balance        float64
Mode            object
Ref             object
dtype: object

Missing Values
Date           0
Time           0
Description    0
Type           0
Amount         0
Balance        0
Mode           0
Ref            0
dtype: int64

Duplicate Rows
18

In [19]:
# AI-assisted: Parsing multiple date formats

df["Date"] = pd.to_datetime(
    df["Date"],
    errors="coerce",
    dayfirst=True
)

print("Unparsed Dates:", df["Date"].isna().sum())

Unparsed Dates: 1184

In [20]:
# AI-assisted: Cleaning Amount column

df["Amount"] = (
    df["Amount"]
    .astype(str)
    .str.replace("₹", "", regex=False)
    .str.replace("Rs.", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

df["Amount"] = pd.to_numeric(
    df["Amount"],
    errors="coerce"
)

print("Unparsed Amounts:", df["Amount"].isna().sum())

Unparsed Amounts: 0

In [21]:
# AI-assisted: Standardizing transaction types

df["Type"] = (
    df["Type"]
    .astype(str)
    .str.lower()
    .str.strip()
)

type_mapping = {
    "dr": "debit",
    "debit": "debit",
    "cr": "credit",
    "credit": "credit"
}

df["Type"] = df["Type"].replace(type_mapping)

print(df["Type"].value_counts())

Type
debit     1322
credit       6
Name: count, dtype: int64

In [22]:
# AI-assisted: Cleaning Mode column

df["Mode"] = (
    df["Mode"]
    .replace("", np.nan)
)

print(df["Mode"].isna().sum())

0

In [23]:
duplicates_before = df.duplicated().sum()

df = df.drop_duplicates()

duplicates_after = df.duplicated().sum()

print("Duplicates Removed:", duplicates_before)
print("Remaining Duplicates:", duplicates_after)

Duplicates Removed: 18
Remaining Duplicates: 0

In [24]:
rows_before = len(df)

df = df.dropna(subset=["Date", "Amount"])

rows_after = len(df)

print("Rows Removed:", rows_before - rows_after)

Rows Removed: 1167

In [25]:
# AI-assisted: Creating date-related features

df["Month"] = df["Date"].dt.month_name()

df["Month_Number"] = df["Date"].dt.month

df["Day"] = df["Date"].dt.day_name()

df["Year"] = df["Date"].dt.year

df["Hour"] = df["Time"].str[:2].astype(int)

df.head()

,Date,Time,Description,Type,Amount,Balance,Mode,Ref,Month,Month_Number,Day,Year,Hour
0,2024-01-01,03:11,AMAZON SELLER SVCS,debit,2462.0,678275.0,UPI,TXN190872,January,1,Monday,2024,3
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,debit,1828.0,-748745.0,UPI,TXN569226,January,1,Monday,2024,14
5,2024-01-01,14:48,BHIM ZEPTO,debit,625.0,677650.0,UPI,TXN370902,January,1,Monday,2024,14
6,2024-01-01,14:50,UPI-UBER-2426@HDFCBANK,debit,148.0,677020.0,UPI,TXN546173,January,1,Monday,2024,14
8,2024-02-01,05:18,POS SWIGGY BANGALORE,debit,537.0,676177.0,UPI,TXN293319,February,2,Thursday,2024,5

In [26]:
print("="*70)
print("TRANSACTION PARSER SUMMARY")
print("="*70)

print(f"Original Rows           : {rows_before}")

print(f"Final Transactions      : {len(df)}")

print(f"Duplicates Removed      : {duplicates_before}")

print(f"Invalid Rows Removed    : {rows_before - rows_after}")

print(f"Unique Transaction Type : {df['Type'].unique()}")

print(f"Missing Amounts         : {df['Amount'].isna().sum()}")

print(f"Missing Dates           : {df['Date'].isna().sum()}")

print(f"Date Range              : {df['Date'].min().date()} to {df['Date'].max().date()}")

print("="*70)

======================================================================
TRANSACTION PARSER SUMMARY
======================================================================
Original Rows           : 1310
Final Transactions      : 143
Duplicates Removed      : 18
Invalid Rows Removed    : 1167
Unique Transaction Type : ['debit' 'credit']
Missing Amounts         : 0
Missing Dates           : 0
Date Range              : 2024-01-01 to 2024-12-06
======================================================================

In [27]:
# AI-assisted: Inspecting transaction descriptions

print("Number of Unique Descriptions:", df["Description"].nunique())

df["Description"].unique()[:50]

Number of Unique Descriptions: 81

array(['AMAZON SELLER SVCS', 'UPI-AMAN-8934@OKAXIS', 'BHIM ZEPTO',
       'UPI-UBER-2426@HDFCBANK', 'POS SWIGGY BANGALORE',
       'ANI Technologies', 'POS SWIGGY-RESTAURANT', 'POS UBER BANGALORE',
       'TWC INDIA', 'UPI-STARBUCKS@AXIS', 'POS BLINKIT',
       'ZOMATO MEDIA P L', 'BHIM SWIGGY', 'OLA CABS', 'UPI-DMART@OKAXIS',
       'POS ZEPTO BANGALORE', 'UPI-MYNTRA@HDFCBANK',
       'BANGALORE ELEC SUPPLY', 'Amazon Pay India',
       'UPI-PRIYA-2221@OKAXIS', 'INSTAMART BANGALORE',
       'UPI-ZOMATO-LIMITED@PAYTM', 'UPI-SWIGGY-7959@HDFCBANK',
       'UPI-SWIGGY-INSTAMART@OKAXIS', 'POS OLA-PRIME',
       'POS EMPIRE RESTAURANT', 'SWIGGY-INSTAMART', 'POS NYKAA BANGALORE',
       'ROPPEN TRANSPORTATION', 'UPI-NYKAA@AXIS', 'UPI-SWIGGY4619@OKAXIS',
       'UPI-FLIPKART@HDFCBANK', 'IMPS ZERODHA-COIN',
       'UPI-THIRDWAVE@OKAXIS', 'UPI-SWIGGY-1309@HDFCBANK',
       'NEFT-TECHCRUSH LABS-SALARY MAY24', 'BHIM-BLINKIT',
       'UPI-ZEPTO-4547@HDFCBANK', 'RAPIDO BIKE TAXI',
       'UPI-RESTAURANT-6377@PAYTM', 'Swiggy*Order', 'COFFEE DAY GLOBAL',
       'FLIPKART INDIA', 'UPI-CCD@HDFCBANK', 'UPI-VIKAS-5416@OKAXIS',
       'UPI-BOOKMYSHOW@HDFCBANK', 'UPI-HOTSTAR@AXIS',
       'UPI-ZOMATO6436@OKICICI', 'NETFLIX.COM', 'BMS MOVIE TICKETS'],
      dtype=object)

In [28]:
# AI-assisted: Vendor keyword dictionary

vendor_dict = {

    "Swiggy": ["SWIGGY", "BUNDL"],

    "Zomato": ["ZOMATO"],

    "Zepto": ["ZEPTO"],

    "Blinkit": ["BLINKIT"],

    "BigBasket": ["BIGBASKET"],

    "Instamart": ["INSTAMART"],

    "Amazon": ["AMAZON", "AMZN", "AMAZONPAY"],

    "Flipkart": ["FLIPKART"],

    "Myntra": ["MYNTRA"],

    "Ajio": ["AJIO"],

    "Nykaa": ["NYKAA"],

    "Uber": ["UBER"],

    "Ola": ["OLA"],

    "Rapido": ["RAPIDO"],

    "IRCTC": ["IRCTC"],

    "BookMyShow": ["BOOKMYSHOW"],

    "Netflix": ["NETFLIX"],

    "Spotify": ["SPOTIFY"],

    "YouTube": ["YOUTUBE"],

    "Hotstar": ["HOTSTAR"],

    "Prime Video": ["PRIME"],

    "Jio": ["JIO"],

    "Airtel": ["AIRTEL"],

    "BSNL": ["BSNL"],

    "ACT": ["ACT"],

    "Bescom": ["BESCOM"],

    "Water Bill": ["BWSSB"],

    "HP Fuel": ["HPCL", "HP PETROL"],

    "Indian Oil": ["IOCL"],

    "Shell": ["SHELL"],

    "Reliance": ["RELIANCE"],

    "DMart": ["DMART"],

    "More": ["MORE"],

    "Starbucks": ["STARBUCKS"],

    "Cafe Coffee Day": ["CCD"],

    "Third Wave Coffee": ["THIRD WAVE"],

    "Zerodha": ["ZERODHA"],

    "Groww": ["GROWW"],

    "Paytm": ["PAYTM"],

    "PhonePe": ["PHONEPE"],

    "Google Pay": ["GPAY"],

    "Cash Withdrawal": ["ATM-WDL", "ATM"],

    "P2P Transfer": ["OKAXIS", "OKHDFC", "OKSBI", "@OK", "@YBL"]
}

In [29]:
# AI-assisted: Vendor extraction

def extract_vendor(description):

    description = str(description).upper()

    for vendor, keywords in vendor_dict.items():

        for keyword in keywords:

            if keyword in description:
                return vendor

    return "Uncategorised"

In [30]:
df["Vendor"] = df["Description"].apply(extract_vendor)

print("Vendor column created successfully!")

Vendor column created successfully!

In [31]:
print("Unique Vendors:", df["Vendor"].nunique())

df["Vendor"].value_counts().head(20)

Unique Vendors: 27

Vendor
Swiggy             28
Uncategorised      27
Zomato             16
Ola                 8
Uber                7
P2P Transfer        5
Zepto               5
Starbucks           4
Zerodha             4
Nykaa               4
Flipkart            4
Cash Withdrawal     3
DMart               3
Amazon              3
Instamart           3
BookMyShow          3
Blinkit             2
Myntra              2
Rapido              2
Cafe Coffee Day     2
Name: count, dtype: int64

In [32]:
uncategorised = df[df["Vendor"] == "Uncategorised"]

print("Uncategorised Transactions:", len(uncategorised))

uncategorised["Description"].unique()[:50]

Uncategorised Transactions: 27

array(['ANI Technologies', 'TWC INDIA', 'BANGALORE ELEC SUPPLY',
       'POS EMPIRE RESTAURANT', 'ROPPEN TRANSPORTATION',
       'NEFT-TECHCRUSH LABS-SALARY MAY24', 'COFFEE DAY GLOBAL',
       'BMS MOVIE TICKETS', 'INNOVATIVE RETAIL', 'AVENUE SUPERMARTS',
       'KIRANAKART TECH', 'POS BANGALORE RESTAURANT',
       'IMPS-RENT-LANDLORD-49966195', 'IMPS-RENT-LANDLORD-35126704',
       'UPI-VI-RECHARGE@HDFCBANK'], dtype=object)

In [33]:
print("="*60)
print("VENDOR CLEANUP AUDIT")
print("="*60)

print("Descriptions that still need mapping:\n")

for desc in sorted(uncategorised["Description"].unique()):
    print("-", desc)

============================================================
VENDOR CLEANUP AUDIT
============================================================
Descriptions that still need mapping:

- ANI Technologies
- AVENUE SUPERMARTS
- BANGALORE ELEC SUPPLY
- BMS MOVIE TICKETS
- COFFEE DAY GLOBAL
- IMPS-RENT-LANDLORD-35126704
- IMPS-RENT-LANDLORD-49966195
- INNOVATIVE RETAIL
- KIRANAKART TECH
- NEFT-TECHCRUSH LABS-SALARY MAY24
- POS BANGALORE RESTAURANT
- POS EMPIRE RESTAURANT
- ROPPEN TRANSPORTATION
- TWC INDIA
- UPI-VI-RECHARGE@HDFCBANK

In [34]:
vendor_dict["Swiggy"].append("BUNDL TECH")

vendor_dict["Amazon"].append("AMZN")

vendor_dict["Blinkit"].append("GROFERS")

In [35]:
print("="*70)
print("VENDOR EXTRACTION SUMMARY")
print("="*70)

print(f"Total Transactions     : {len(df)}")
print(f"Unique Vendors         : {df['Vendor'].nunique()}")
print(f"Uncategorised Records  : {(df['Vendor']=='Uncategorised').sum()}")

print("\nTop 10 Vendors")

print(df["Vendor"].value_counts().head(10))

print("="*70)

======================================================================
VENDOR EXTRACTION SUMMARY
======================================================================
Total Transactions     : 143
Unique Vendors         : 27
Uncategorised Records  : 27

Top 10 Vendors
Vendor
Swiggy           28
Uncategorised    27
Zomato           16
Ola               8
Uber              7
P2P Transfer      5
Zepto             5
Starbucks         4
Zerodha           4
Nykaa             4
Name: count, dtype: int64
======================================================================

In [36]:
# AI-assisted: Vendor to Category mapping

category_dict = {

    # Food Delivery
    "Swiggy": "Food Delivery",
    "Zomato": "Food Delivery",

    # Quick Commerce
    "Zepto": "Quick Commerce",
    "Blinkit": "Quick Commerce",
    "Instamart": "Quick Commerce",

    # Groceries
    "BigBasket": "Groceries",
    "DMart": "Groceries",
    "More": "Groceries",

    # E-commerce
    "Amazon": "E-commerce",
    "Flipkart": "E-commerce",
    "Myntra": "E-commerce",
    "Ajio": "E-commerce",
    "Nykaa": "E-commerce",

    # Transport
    "Uber": "Transport",
    "Ola": "Transport",
    "Rapido": "Transport",
    "IRCTC": "Transport",

    # Entertainment
    "BookMyShow": "Entertainment",

    # Subscriptions
    "Netflix": "Subscriptions",
    "Spotify": "Subscriptions",
    "Prime Video": "Subscriptions",
    "Hotstar": "Subscriptions",
    "YouTube": "Subscriptions",

    # Cafe
    "Starbucks": "Cafe",
    "Cafe Coffee Day": "Cafe",
    "Third Wave Coffee": "Cafe",

    # Investments
    "Zerodha": "Investments",
    "Groww": "Investments",

    # Utilities
    "Jio": "Utilities",
    "Airtel": "Utilities",
    "BSNL": "Utilities",
    "ACT": "Utilities",
    "Bescom": "Utilities",
    "Water Bill": "Utilities",

    # Fuel
    "Indian Oil": "Fuel",
    "HP Fuel": "Fuel",
    "Shell": "Fuel",

    # Wallets
    "Paytm": "Wallet",
    "PhonePe": "Wallet",
    "Google Pay": "Wallet",

    # Special Categories
    "Cash Withdrawal": "Cash Withdrawal",
    "P2P Transfer": "Personal Transfer"
}

In [37]:
# AI-assisted: Category mapping

df["Category"] = df["Vendor"].map(category_dict)

df["Category"] = df["Category"].fillna("Others")

print("Category column created successfully.")

Category column created successfully.

In [38]:
print("="*60)
print("CATEGORY DISTRIBUTION")
print("="*60)

print(df["Category"].value_counts())

============================================================
CATEGORY DISTRIBUTION
============================================================
Category
Food Delivery        44
Others               27
Transport            17
E-commerce           13
Quick Commerce       10
Cafe                  7
Personal Transfer     5
Investments           5
Groceries             4
Entertainment         3
Cash Withdrawal       3
Wallet                2
Subscriptions         2
Fuel                  1
Name: count, dtype: int64

In [39]:
missing_category = df[df["Category"] == "Others"]

print("Transactions in 'Others':", len(missing_category))

missing_category[["Description", "Vendor"]].head(20)

Transactions in 'Others': 27

                          Description         Vendor
16                   ANI Technologies  Uncategorised
25                          TWC INDIA  Uncategorised
85              BANGALORE ELEC SUPPLY  Uncategorised
252             POS EMPIRE RESTAURANT  Uncategorised
258                         TWC INDIA  Uncategorised
261             ROPPEN TRANSPORTATION  Uncategorised
266             POS EMPIRE RESTAURANT  Uncategorised
276             POS EMPIRE RESTAURANT  Uncategorised
438  NEFT-TECHCRUSH LABS-SALARY MAY24  Uncategorised
440                  ANI Technologies  Uncategorised
461                 COFFEE DAY GLOBAL  Uncategorised
506                 BMS MOVIE TICKETS  Uncategorised
515                 INNOVATIVE RETAIL  Uncategorised
521                 AVENUE SUPERMARTS  Uncategorised
662                  ANI Technologies  Uncategorised
742                         TWC INDIA  Uncategorised
880  NEFT-TECHCRUSH LABS-SALARY MAY24  Uncategorised
883             POS EMPIRE RESTAURANT  Uncategorised
901                   KIRANAKART TECH  Uncategorised
903          POS BANGALORE RESTAURANT  Uncategorised

In [40]:
category_count = (
    df.groupby("Category")
      .size()
      .sort_values(ascending=False)
)

print(category_count)

Category
Food Delivery        44
Others               27
Transport            17
E-commerce           13
Quick Commerce       10
Cafe                  7
Personal Transfer     5
Investments           5
Groceries             4
Cash Withdrawal       3
Entertainment         3
Subscriptions         2
Wallet                2
Fuel                  1
dtype: int64

In [41]:
debit_df = df[df["Type"] == "debit"].copy()

print("Debit Transactions:", len(debit_df))

Debit Transactions: 141

In [42]:
category_spend = (
    debit_df
    .groupby("Category")["Amount"]
    .sum()
    .sort_values(ascending=False)
)

print(category_spend)

Category
Investments          64496.0
Others               53139.0
E-commerce           36416.0
Food Delivery        19617.0
Personal Transfer     5429.0
Groceries             5242.0
Transport             5145.0
Quick Commerce        4782.0
Cash Withdrawal       3000.0
Cafe                  2434.0
Entertainment         1740.0
Subscriptions         1683.0
Wallet                1100.0
Fuel                  1087.0
Name: Amount, dtype: float64

In [43]:
total_debit = debit_df["Amount"].sum()

category_percentage = (
    category_spend / total_debit * 100
).round(2)

category_summary = pd.DataFrame({
    "Amount": category_spend,
    "Percentage": category_percentage
})

category_summary

                    Amount  Percentage
Category
Investments        64496.0       31.41
Others             53139.0       25.88
E-commerce         36416.0       17.74
Food Delivery      19617.0        9.55
Personal Transfer   5429.0        2.64
Groceries           5242.0        2.55
Transport           5145.0        2.51
Quick Commerce      4782.0        2.33
Cash Withdrawal     3000.0        1.46
Cafe                2434.0        1.19
Entertainment       1740.0        0.85
Subscriptions       1683.0        0.82
Wallet              1100.0        0.54
Fuel                1087.0        0.53

In [44]:
vendor_spend = (
    debit_df
    .groupby("Vendor")["Amount"]
    .sum()
    .sort_values(ascending=False)
)

vendor_spend.head(10)

Vendor
Zerodha          60000.0
Uncategorised    53139.0
Myntra           13629.0
Swiggy           12638.0
Flipkart         10041.0
Amazon            7550.0
Zomato            6979.0
P2P Transfer      5429.0
Nykaa             5196.0
Groww             4496.0
Name: Amount, dtype: float64

In [45]:
print("="*70)
print("CATEGORY TAGGER SUMMARY")
print("="*70)

print(f"Unique Categories : {df['Category'].nunique()}")

print("\nTop Categories by Transactions")
print(df["Category"].value_counts().head())

print("\nTop Categories by Spending")
print(category_summary.head())

print("="*70)

======================================================================
CATEGORY TAGGER SUMMARY
======================================================================
Unique Categories : 14

Top Categories by Transactions
Category
Food Delivery     44
Others            27
Transport         17
E-commerce        13
Quick Commerce    10
Name: count, dtype: int64

Top Categories by Spending
                    Amount  Percentage
Category
Investments        64496.0       31.41
Others             53139.0       25.88
E-commerce         36416.0       17.74
Food Delivery      19617.0        9.55
Personal Transfer   5429.0        2.64
======================================================================

In [46]:
# AI-assisted: Calculating financial overview metrics

total_credit = df[df["Type"] == "credit"]["Amount"].sum()

total_debit = df[df["Type"] == "debit"]["Amount"].sum()

net_change = total_credit - total_debit

savings_rate = (net_change / total_credit) * 100

transaction_count = len(df)

unique_vendors = df["Vendor"].nunique()

In [47]:
top_categories = (
    debit_df
    .groupby("Category")["Amount"]
    .sum()
    .sort_values(ascending=False)
    .head(5)
)

top_categories

Category
Investments          64496.0
Others               53139.0
E-commerce           36416.0
Food Delivery        19617.0
Personal Transfer     5429.0
Name: Amount, dtype: float64

In [48]:
top_vendors = (
    debit_df
    .groupby("Vendor")
    .agg(
        Total_Spend=("Amount","sum"),
        Transactions=("Vendor","count")
    )
    .sort_values(
        by="Total_Spend",
        ascending=False
    )
    .head(5)
)

top_vendors

               Total_Spend  Transactions
Vendor
Zerodha            60000.0             4
Uncategorised      53139.0            25
Myntra             13629.0             2
Swiggy             12638.0            28
Flipkart           10041.0             4

In [49]:
print("="*70)
print("EXECUTIVE SUMMARY")
print("="*70)

print(f"Total Credits        : ₹{total_credit:,.2f}")

print(f"Total Debits         : ₹{total_debit:,.2f}")

print(f"Net Change           : ₹{net_change:,.2f}")

print(f"Savings Rate         : {savings_rate:.2f}%")

print(f"Total Transactions   : {transaction_count}")

print(f"Unique Vendors       : {unique_vendors}")

print("="*70)

======================================================================
EXECUTIVE SUMMARY
======================================================================
Total Credits        : ₹170,094.00
Total Debits         : ₹205,310.00
Net Change           : ₹-35,216.00
Savings Rate         : -20.70%
Total Transactions   : 143
Unique Vendors       : 27
======================================================================

In [50]:
if net_change > 0:
    status = "Healthy Savings ✅"

elif net_change == 0:
    status = "Break Even"

else:
    status = "Overspending ⚠️"

print("Financial Status :", status)

Financial Status : Overspending ⚠️

In [51]:
category_table = top_categories.reset_index()

category_table.columns = ["Category","Amount"]

category_table["Percentage"] = (
    category_table["Amount"] /
    total_debit * 100
).round(2)

category_table

            Category   Amount  Percentage
0        Investments  64496.0       31.41
1             Others  53139.0       25.88
2         E-commerce  36416.0       17.74
3      Food Delivery  19617.0        9.55
4  Personal Transfer   5429.0        2.64

In [52]:
print("="*70)
print("TOP CATEGORIES")
print("="*70)

for _, row in category_table.iterrows():

    bar = "#" * int(row["Percentage"]//2)

    print(f"{row['Category']:<20} {bar:<25} {row['Percentage']:>6.2f}%")

======================================================================
TOP CATEGORIES
======================================================================
Investments          ###############            31.41%
Others               ############               25.88%
E-commerce           ########                   17.74%
Food Delivery        ####                        9.55%
Personal Transfer    #                           2.64%

In [53]:
print("="*70)
print("TOP VENDORS")
print("="*70)

for vendor, row in top_vendors.iterrows():

    print(
        f"{vendor:<20}"
        f"₹{row['Total_Spend']:>12,.2f}"
        f" ({int(row['Transactions'])} transactions)"
    )

======================================================================
TOP VENDORS
======================================================================
Zerodha             ₹   60,000.00 (4 transactions)
Uncategorised       ₹   53,139.00 (25 transactions)
Myntra              ₹   13,629.00 (2 transactions)
Swiggy              ₹   12,638.00 (28 transactions)
Flipkart            ₹   10,041.00 (4 transactions)

In [54]:
print("="*70)
print("EXECUTIVE INSIGHTS")
print("="*70)

highest_category = category_table.iloc[0]

highest_vendor = top_vendors.iloc[0]

print(f"• Highest spending category : {highest_category['Category']}")

print(f"• Category Share            : {highest_category['Percentage']:.2f}%")

print(f"• Top Vendor               : {top_vendors.index[0]}")

print(f"• Overall Financial Status : {status}")

======================================================================
EXECUTIVE INSIGHTS
======================================================================
• Highest spending category : Investments
• Category Share            : 31.41%
• Top Vendor               : Zerodha
• Overall Financial Status : Overspending ⚠️

In [55]:
print("="*70)
print("SPENDING OVERVIEW COMPLETED")
print("="*70)

print(f"Credits Analysed      : ₹{total_credit:,.2f}")

print(f"Debits Analysed       : ₹{total_debit:,.2f}")

print(f"Net Balance Change    : ₹{net_change:,.2f}")

print(f"Savings Rate          : {savings_rate:.2f}%")

print(f"Top Category          : {highest_category['Category']}")

print(f"Top Vendor            : {top_vendors.index[0]}")

print("="*70)

======================================================================
SPENDING OVERVIEW COMPLETED
======================================================================
Credits Analysed      : ₹170,094.00
Debits Analysed       : ₹205,310.00
Net Balance Change    : ₹-35,216.00
Savings Rate          : -20.70%
Top Category          : Investments
Top Vendor            : Zerodha
======================================================================

In [56]:
# AI-assisted: Monthly spending pivot table

monthly_pivot = debit_df.pivot_table(
    values="Amount",
    index="Category",
    columns="Month_Number",
    aggfunc="sum",
    fill_value=0
)

monthly_pivot

Month_Number,1,2,3,4,5,6,7,8,9,10,11,12
Category,,,,,,,,,,,,
Cafe,295.0,355.0,0.0,447.0,166.0,0.0,0.0,362.0,0.0,0.0,809.0,0.0
Cash Withdrawal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2500.0,500.0
E-commerce,6972.0,996.0,2147.0,3311.0,0.0,4868.0,2425.0,860.0,10745.0,0.0,0.0,4092.0
Entertainment,0.0,0.0,0.0,343.0,0.0,0.0,562.0,0.0,0.0,835.0,0.0,0.0
Food Delivery,1180.0,3454.0,2862.0,632.0,1159.0,1636.0,1686.0,1446.0,712.0,183.0,1909.0,2758.0
Fuel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1087.0
Groceries,0.0,0.0,1213.0,0.0,0.0,0.0,1257.0,1862.0,0.0,0.0,0.0,910.0
Investments,0.0,0.0,0.0,0.0,0.0,0.0,15000.0,34496.0,0.0,0.0,0.0,15000.0
Others,2255.0,267.0,19416.0,513.0,18753.0,794.0,368.0,1762.0,421.0,2692.0,766.0,5132.0
Personal Transfer,1828.0,0.0,0.0,0.0,0.0,1860.0,0.0,229.0,246.0,0.0,0.0,1266.0
Quick Commerce,1616.0,697.0,0.0,0.0,502.0,0.0,510.0,0.0,1110.0,0.0,347.0,0.0
Subscriptions,0.0,0.0,0.0,0.0,0.0,0.0,1473.0,0.0,210.0,0.0,0.0,0.0
Transport,826.0,621.0,439.0,0.0,431.0,134.0,351.0,366.0,710.0,1232.0,35.0,0.0
Wallet,0.0,0.0,501.0,0.0,0.0,0.0,0.0,0.0,0.0,599.0,0.0,0.0

In [57]:
month_names = {
    1:"Jan",
    2:"Feb",
    3:"Mar",
    4:"Apr",
    5:"May",
    6:"Jun"
}

monthly_pivot.rename(columns=month_names, inplace=True)

monthly_pivot

Month_Number,Jan,Feb,Mar,Apr,May,Jun,7,8,9,10,11,12
Category,,,,,,,,,,,,
Cafe,295.0,355.0,0.0,447.0,166.0,0.0,0.0,362.0,0.0,0.0,809.0,0.0
Cash Withdrawal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2500.0,500.0
E-commerce,6972.0,996.0,2147.0,3311.0,0.0,4868.0,2425.0,860.0,10745.0,0.0,0.0,4092.0
Entertainment,0.0,0.0,0.0,343.0,0.0,0.0,562.0,0.0,0.0,835.0,0.0,0.0
Food Delivery,1180.0,3454.0,2862.0,632.0,1159.0,1636.0,1686.0,1446.0,712.0,183.0,1909.0,2758.0
Fuel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1087.0
Groceries,0.0,0.0,1213.0,0.0,0.0,0.0,1257.0,1862.0,0.0,0.0,0.0,910.0
Investments,0.0,0.0,0.0,0.0,0.0,0.0,15000.0,34496.0,0.0,0.0,0.0,15000.0
Others,2255.0,267.0,19416.0,513.0,18753.0,794.0,368.0,1762.0,421.0,2692.0,766.0,5132.0
Personal Transfer,1828.0,0.0,0.0,0.0,0.0,1860.0,0.0,229.0,246.0,0.0,0.0,1266.0
Quick Commerce,1616.0,697.0,0.0,0.0,502.0,0.0,510.0,0.0,1110.0,0.0,347.0,0.0
Subscriptions,0.0,0.0,0.0,0.0,0.0,0.0,1473.0,0.0,210.0,0.0,0.0,0.0
Transport,826.0,621.0,439.0,0.0,431.0,134.0,351.0,366.0,710.0,1232.0,35.0,0.0
Wallet,0.0,0.0,501.0,0.0,0.0,0.0,0.0,0.0,0.0,599.0,0.0,0.0

In [58]:
monthly_total = (
    debit_df
    .groupby("Month_Number")["Amount"]
    .sum()
    .sort_index()
)

monthly_total.index = monthly_total.index.map(month_names)

monthly_total

Month_Number
Jan    14972.0
Feb     6390.0
Mar    26578.0
Apr     5246.0
May    21011.0
Jun     9292.0
NaN    23632.0
NaN    41383.0
NaN    14154.0
NaN     5541.0
NaN     6366.0
NaN    30745.0
Name: Amount, dtype: float64

In [59]:
print("="*70)
print("MONTHLY SPENDING TREND")
print("="*70)

max_amount = monthly_total.max()

for month, amount in monthly_total.items():

    bar_length = int((amount / max_amount) * 40)

    bar = "#" * bar_length

    print(f"{month:<5} ₹{amount:>12,.2f} {bar}")

======================================================================
MONTHLY SPENDING TREND
======================================================================
Jan   ₹   14,972.00 ##############
Feb   ₹    6,390.00 ######
Mar   ₹   26,578.00 #########################
Apr   ₹    5,246.00 #####
May   ₹   21,011.00 ####################
Jun   ₹    9,292.00 ########
nan   ₹   23,632.00 ######################
nan   ₹   41,383.00 ########################################
nan   ₹   14,154.00 #############
nan   ₹    5,541.00 #####
nan   ₹    6,366.00 ######
nan   ₹   30,745.00 #############################

In [60]:
highest_month = monthly_total.idxmax()
lowest_month = monthly_total.idxmin()

print("Highest Spending Month :", highest_month)

print("Lowest Spending Month  :", lowest_month)

Highest Spending Month : nan
Lowest Spending Month  : Apr

In [61]:
monthly_growth = (
    monthly_total
    .pct_change()
    *100
).round(2)

monthly_growth

Month_Number
Jan       NaN
Feb    -57.32
Mar    315.93
Apr    -80.26
May    300.51
Jun    -55.78
NaN    154.33
NaN     75.11
NaN    -65.80
NaN    -60.85
NaN     14.89
NaN    382.96
Name: Amount, dtype: float64

In [62]:
growth_table = monthly_pivot.copy()

growth_table["Growth_%"] = (
    (
        growth_table["Jun"] -
        growth_table["Jan"]
    )
    /
    growth_table["Jan"].replace(0,np.nan)
) *100

growth_table["Growth_%"] = growth_table["Growth_%"].round(2)

growth_table

Month_Number,Jan,Feb,Mar,Apr,May,Jun,7,8,9,10,11,12,Growth_%
Category,,,,,,,,,,,,,
Cafe,295.0,355.0,0.0,447.0,166.0,0.0,0.0,362.0,0.0,0.0,809.0,0.0,-100.00
Cash Withdrawal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2500.0,500.0,NaN
E-commerce,6972.0,996.0,2147.0,3311.0,0.0,4868.0,2425.0,860.0,10745.0,0.0,0.0,4092.0,-30.18
Entertainment,0.0,0.0,0.0,343.0,0.0,0.0,562.0,0.0,0.0,835.0,0.0,0.0,NaN
Food Delivery,1180.0,3454.0,2862.0,632.0,1159.0,1636.0,1686.0,1446.0,712.0,183.0,1909.0,2758.0,38.64
Fuel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1087.0,NaN
Groceries,0.0,0.0,1213.0,0.0,0.0,0.0,1257.0,1862.0,0.0,0.0,0.0,910.0,NaN
Investments,0.0,0.0,0.0,0.0,0.0,0.0,15000.0,34496.0,0.0,0.0,0.0,15000.0,NaN
Others,2255.0,267.0,19416.0,513.0,18753.0,794.0,368.0,1762.0,421.0,2692.0,766.0,5132.0,-64.79
Personal Transfer,1828.0,0.0,0.0,0.0,0.0,1860.0,0.0,229.0,246.0,0.0,0.0,1266.0,1.75
Quick Commerce,1616.0,697.0,0.0,0.0,502.0,0.0,510.0,0.0,1110.0,0.0,347.0,0.0,-100.00
Subscriptions,0.0,0.0,0.0,0.0,0.0,0.0,1473.0,0.0,210.0,0.0,0.0,0.0,NaN
Transport,826.0,621.0,439.0,0.0,431.0,134.0,351.0,366.0,710.0,1232.0,35.0,0.0,-83.78
Wallet,0.0,0.0,501.0,0.0,0.0,0.0,0.0,0.0,0.0,599.0,0.0,0.0,NaN

In [63]:
fastest_growth = growth_table["Growth_%"].idxmax()

growth_value = growth_table["Growth_%"].max()

print("Fastest Growing Category")

print(f"{fastest_growth} ({growth_value:.2f}%)")

Fastest Growing Category
Food Delivery (38.64%)

In [64]:
decline_category = growth_table["Growth_%"].idxmin()

decline_value = growth_table["Growth_%"].min()

print("Largest Decline")

print(f"{decline_category} ({decline_value:.2f}%)")

Largest Decline
Cafe (-100.00%)

In [65]:
trend_summary = pd.DataFrame({

    "Monthly Spend": monthly_total,

    "Growth %": monthly_growth

})

trend_summary

              Monthly Spend  Growth %
Month_Number
Jan                 14972.0       NaN
Feb                  6390.0    -57.32
Mar                 26578.0    315.93
Apr                  5246.0    -80.26
May                 21011.0    300.51
Jun                  9292.0    -55.78
NaN                 23632.0    154.33
NaN                 41383.0     75.11
NaN                 14154.0    -65.80
NaN                  5541.0    -60.85
NaN                  6366.0     14.89
NaN                 30745.0    382.96

In [66]:
print("="*70)
print("MONTHLY TREND INSIGHTS")
print("="*70)

print(f"Highest Spending Month : {highest_month}")

print(f"Lowest Spending Month  : {lowest_month}")

print(f"Fastest Growing Category : {fastest_growth}")

print(f"Growth Percentage : {growth_value:.2f}%")

print(f"Largest Decline Category : {decline_category}")

print(f"Decline Percentage : {decline_value:.2f}%")

======================================================================
MONTHLY TREND INSIGHTS
======================================================================
Highest Spending Month : nan
Lowest Spending Month  : Apr
Fastest Growing Category : Food Delivery
Growth Percentage : 38.64%
Largest Decline Category : Cafe
Decline Percentage : -100.00%

In [67]:
food_monthly = monthly_pivot.loc["Food Delivery"]

print("="*70)
print("FOOD DELIVERY TREND")
print("="*70)

max_food = food_monthly.max()

for month, amount in food_monthly.items():

    bar = "#" * int((amount/max_food)*30)

    print(f"{month:<5} ₹{amount:>10,.2f} {bar}")

======================================================================
FOOD DELIVERY TREND
======================================================================
Jan   ₹  1,180.00 ##########
Feb   ₹  3,454.00 ##############################
Mar   ₹  2,862.00 ########################
Apr   ₹    632.00 #####
May   ₹  1,159.00 ##########
Jun   ₹  1,636.00 ##############
7     ₹  1,686.00 ##############
8     ₹  1,446.00 ############
9     ₹    712.00 ######
10    ₹    183.00 #
11    ₹  1,909.00 ################
12    ₹  2,758.00 #######################

In [68]:
print("="*70)
print("MONTHLY TREND ANALYSIS COMPLETED")
print("="*70)

print(f"Months Analysed : {len(monthly_total)}")

print(f"Highest Month   : {highest_month}")

print(f"Lowest Month    : {lowest_month}")

print(f"Fastest Growth  : {fastest_growth}")

print(f"Largest Decline : {decline_category}")

print("="*70)

======================================================================
MONTHLY TREND ANALYSIS COMPLETED
======================================================================
Months Analysed : 12
Highest Month   : nan
Lowest Month    : Apr
Fastest Growth  : Food Delivery
Largest Decline : Cafe
======================================================================

In [69]:
# AI-assisted: Verifying hour extraction

print("Hour Range")

print("Minimum Hour :", debit_df["Hour"].min())

print("Maximum Hour :", debit_df["Hour"].max())

print()

print(debit_df["Hour"].value_counts().sort_index())

Hour Range
Minimum Hour : 0
Maximum Hour : 23

Hour
0      5
1      2
2      2
3      2
4      2
5      3
6      2
7      3
8      4
9      6
10    11
11     8
12     9
13     9
14    10
15     7
16     6
17     7
18    13
19     4
20     9
21     9
22     5
23     3
Name: count, dtype: int64

In [70]:
hourly_spend = (
    debit_df
    .groupby("Hour")["Amount"]
    .sum()
    .sort_index()
)

hourly_spend

Hour
0      1820.0
1      1462.0
2      1015.0
3      3228.0
4     15413.0
5      5458.0
6      1948.0
7      1668.0
8      3542.0
9      2678.0
10    49574.0
11     8739.0
12     3729.0
13    22872.0
14    23670.0
15     3765.0
16     2753.0
17     3200.0
18    14213.0
19     5950.0
20    16097.0
21     7361.0
22     3728.0
23     1427.0
Name: Amount, dtype: float64

In [71]:
hourly_transactions = (
    debit_df
    .groupby("Hour")
    .size()
)

hourly_transactions

Hour
0      5
1      2
2      2
3      2
4      2
5      3
6      2
7      3
8      4
9      6
10    11
11     8
12     9
13     9
14    10
15     7
16     6
17     7
18    13
19     4
20     9
21     9
22     5
23     3
dtype: int64

In [72]:
print("="*70)
print("HOURLY SPENDING")
print("="*70)

max_amount = hourly_spend.max()

for hour, amount in hourly_spend.items():

    bar = "#" * int((amount/max_amount)*40)

    print(f"{hour:02d}:00 ₹{amount:>10,.2f} {bar}")

======================================================================
HOURLY SPENDING
======================================================================
00:00 ₹  1,820.00 #
01:00 ₹  1,462.00 #
02:00 ₹  1,015.00
03:00 ₹  3,228.00 ##
04:00 ₹ 15,413.00 ############
05:00 ₹  5,458.00 ####
06:00 ₹  1,948.00 #
07:00 ₹  1,668.00 #
08:00 ₹  3,542.00 ##
09:00 ₹  2,678.00 ##
10:00 ₹ 49,574.00 ########################################
11:00 ₹  8,739.00 #######
12:00 ₹  3,729.00 ###
13:00 ₹ 22,872.00 ##################
14:00 ₹ 23,670.00 ###################
15:00 ₹  3,765.00 ###
16:00 ₹  2,753.00 ##
17:00 ₹  3,200.00 ##
18:00 ₹ 14,213.00 ###########
19:00 ₹  5,950.00 ####
20:00 ₹ 16,097.00 ############
21:00 ₹  7,361.00 #####
22:00 ₹  3,728.00 ###
23:00 ₹  1,427.00 #

In [73]:
hour_matrix = debit_df.pivot_table(
    values="Amount",
    index="Category",
    columns="Hour",
    aggfunc="sum",
    fill_value=0
)

hour_matrix

Hour,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
Category,,,,,,,,,,,,,,,,,,,,,
Cafe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,376.0,...,166.0,0.0,447.0,295.0,0.0,0.0,0.0,0.0,0.0,0.0
Cash Withdrawal,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,500.0,...,500.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
E-commerce,0.0,842.0,0.0,2462.0,0.0,0.0,1626.0,860.0,0.0,0.0,...,0.0,1583.0,0.0,0.0,6899.0,4092.0,10745.0,3311.0,0.0,0.0
Entertainment,562.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,835.0,0.0,0.0,0.0,0.0,0.0,343.0,0.0
Food Delivery,394.0,0.0,318.0,0.0,413.0,537.0,0.0,0.0,369.0,383.0,...,368.0,1274.0,377.0,919.0,1517.0,771.0,1477.0,2078.0,1525.0,844.0
Fuel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1087.0,0.0,0.0,0.0,0.0
Groceries,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,910.0,0.0,1257.0,0.0,0.0,0.0
Investments,0.0,0.0,0.0,0.0,15000.0,4496.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Others,433.0,620.0,0.0,766.0,0.0,0.0,0.0,421.0,2671.0,272.0,...,18000.0,0.0,352.0,1786.0,3978.0,0.0,2267.0,0.0,0.0,0.0
Personal Transfer,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1828.0,0.0,246.0,0.0,0.0,0.0,0.0,1266.0,1860.0,0.0
Quick Commerce,0.0,0.0,697.0,0.0,0.0,0.0,0.0,0.0,502.0,791.0,...,1152.0,0.0,0.0,200.0,543.0,0.0,0.0,0.0,0.0,583.0
Subscriptions,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1473.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Transport,431.0,0.0,0.0,0.0,0.0,425.0,322.0,387.0,0.0,356.0,...,183.0,908.0,496.0,0.0,366.0,0.0,351.0,706.0,0.0,0.0
Wallet,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [74]:
print("="*70)
print("PEAK SPENDING HOUR BY CATEGORY")
print("="*70)

for category in hour_matrix.index:

    peak_hour = hour_matrix.loc[category].idxmax()

    peak_amount = hour_matrix.loc[category].max()

    print(
        f"{category:<22}"
        f"{peak_hour:02d}:00"
        f"   ₹{peak_amount:,.2f}"
    )

======================================================================
PEAK SPENDING HOUR BY CATEGORY
======================================================================
Cafe                  10:00   ₹1,150.00
Cash Withdrawal       10:00   ₹2,000.00
E-commerce            20:00   ₹10,745.00
Entertainment         16:00   ₹835.00
Food Delivery         12:00   ₹2,791.00
Fuel                  19:00   ₹1,087.00
Groceries             11:00   ₹3,075.00
Investments           10:00   ₹45,000.00
Others                13:00   ₹20,255.00
Personal Transfer     22:00   ₹1,860.00
Quick Commerce        14:00   ₹1,152.00
Subscriptions         14:00   ₹1,473.00
Transport             15:00   ₹908.00
Wallet                10:00   ₹599.00

In [75]:
food_df = debit_df[
    debit_df["Category"]=="Food Delivery"
]

late_night = food_df[
    (food_df["Hour"]>=21) |
    (food_df["Hour"]<=2)
]

late_percentage = (
    len(late_night) /
    len(food_df)
) *100

print(f"Late Night Food Orders : {late_percentage:.2f}%")

Late Night Food Orders : 25.00%

In [76]:
cafe_df = debit_df[
    debit_df["Category"]=="Cafe"
]

morning_cafe = cafe_df[
    (cafe_df["Hour"]>=8) &
    (cafe_df["Hour"]<=11)
]

morning_percentage = (
    len(morning_cafe) /
    len(cafe_df)
)*100

print(f"Morning Cafe Visits : {morning_percentage:.2f}%")

Morning Cafe Visits : 57.14%

In [77]:
busiest_hour = hourly_transactions.idxmax()

busiest_transactions = hourly_transactions.max()

print("Busiest Spending Hour")

print(f"{busiest_hour:02d}:00")

print(f"Transactions : {busiest_transactions}")

Busiest Spending Hour
18:00
Transactions : 13

In [78]:
quietest_hour = hourly_transactions.idxmin()

quietest_transactions = hourly_transactions.min()

print("Quietest Hour")

print(f"{quietest_hour:02d}:00")

print(f"Transactions : {quietest_transactions}")

Quietest Hour
01:00
Transactions : 2

In [79]:
print("="*70)
print("TIME-OF-DAY INSIGHTS")
print("="*70)

print(f"Peak Spending Hour      : {busiest_hour:02d}:00")

print(f"Late Night Food Orders  : {late_percentage:.2f}%")

print(f"Morning Cafe Visits     : {morning_percentage:.2f}%")

if late_percentage > 50:
    print("Lifestyle Pattern       : Late Night Snacker")

else:
    print("Lifestyle Pattern       : Balanced Eating Schedule")

======================================================================
TIME-OF-DAY INSIGHTS
======================================================================
Peak Spending Hour      : 18:00
Late Night Food Orders  : 25.00%
Morning Cafe Visits     : 57.14%
Lifestyle Pattern       : Balanced Eating Schedule

In [80]:
hour_summary = pd.DataFrame({

    "Transactions": hourly_transactions,

    "Spend": hourly_spend

})

hour_summary

      Transactions    Spend
Hour
0                5   1820.0
1                2   1462.0
2                2   1015.0
3                2   3228.0
4                2  15413.0
5                3   5458.0
6                2   1948.0
7                3   1668.0
8                4   3542.0
9                6   2678.0
10              11  49574.0
11               8   8739.0
12               9   3729.0
13               9  22872.0
14              10  23670.0
15               7   3765.0
16               6   2753.0
17               7   3200.0
18              13  14213.0
19               4   5950.0
20               9  16097.0
21               9   7361.0
22               5   3728.0
23               3   1427.0

In [81]:
print("="*70)
print("TIME-OF-DAY ANALYSIS COMPLETED")
print("="*70)

print(f"Hours Analysed          : {len(hourly_transactions)}")

print(f"Peak Hour               : {busiest_hour:02d}:00")

print(f"Late Night Food         : {late_percentage:.2f}%")

print(f"Morning Cafe            : {morning_percentage:.2f}%")

print("="*70)

======================================================================
TIME-OF-DAY ANALYSIS COMPLETED
======================================================================
Hours Analysed          : 24
Peak Hour               : 18:00
Late Night Food         : 25.00%
Morning Cafe            : 57.14%
======================================================================

In [82]:
# AI-assisted: Computing category statistics for anomaly detection

category_mean = (
    debit_df
    .groupby("Category")["Amount"]
    .transform("mean")
)

category_mean.head()

0    2801.230769
3    1085.800000
5     478.200000
6     302.647059
8     445.840909
Name: Amount, dtype: float64

In [83]:
category_std = (
    debit_df
    .groupby("Category")["Amount"]
    .transform("std")
)

category_std.head()

0    2585.550688
3     809.643255
5     206.129840
6     140.335287
8     131.648041
Name: Amount, dtype: float64

In [84]:
debit_df["Z_Score"] = (
    (debit_df["Amount"] - category_mean)
    / category_std
)

debit_df["Z_Score"] = debit_df["Z_Score"].fillna(0)

debit_df.head()

,Date,Time,Description,Type,Amount,Balance,Mode,Ref,Month,Month_Number,Day,Year,Hour,Vendor,Category,Z_Score
0,2024-01-01,03:11,AMAZON SELLER SVCS,debit,2462.0,678275.0,UPI,TXN190872,January,1,Monday,2024,3,Amazon,E-commerce,-0.131203
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,debit,1828.0,-748745.0,UPI,TXN569226,January,1,Monday,2024,14,P2P Transfer,Personal Transfer,0.916700
5,2024-01-01,14:48,BHIM ZEPTO,debit,625.0,677650.0,UPI,TXN370902,January,1,Monday,2024,14,Zepto,Quick Commerce,0.712172
6,2024-01-01,14:50,UPI-UBER-2426@HDFCBANK,debit,148.0,677020.0,UPI,TXN546173,January,1,Monday,2024,14,Uber,Transport,-1.101983
8,2024-02-01,05:18,POS SWIGGY BANGALORE,debit,537.0,676177.0,UPI,TXN293319,February,2,Thursday,2024,5,Swiggy,Food Delivery,0.692445

In [85]:
anomalies = debit_df[
    debit_df["Z_Score"] > 2
].copy()

print("Number of Anomalies")

print(len(anomalies))

Number of Anomalies
3

In [86]:
anomalies = anomalies.sort_values(
    by="Z_Score",
    ascending=False
)

anomalies.head()

,Date,Time,Description,Type,Amount,Balance,Mode,Ref,Month,Month_Number,Day,Year,Hour,Vendor,Category,Z_Score
913,2024-05-05,13:23,IMPS-RENT-LANDLORD-49966195,debit,18000.0,653166.0,IMPS,TXN681343,May,5,Sunday,2024,13,Uncategorised,Others,3.291095
1128,2024-03-06,14:21,IMPS-RENT-LANDLORD-35126704,debit,18000.0,702079.0,IMPS,TXN540552,March,3,Wednesday,2024,14,Uncategorised,Others,3.291095
70,2024-09-01,20:00,UPI-MYNTRA@HDFCBANK,debit,10745.0,-370896.0,UPI,TXN947220,September,9,Sunday,2024,20,Myntra,E-commerce,3.072370

In [87]:
anomaly_report = anomalies[[
    "Date",
    "Vendor",
    "Category",
    "Amount",
    "Z_Score"
]]

anomaly_report.head(10)

           Date         Vendor    Category   Amount   Z_Score
913  2024-05-05  Uncategorised      Others  18000.0  3.291095
1128 2024-03-06  Uncategorised      Others  18000.0  3.291095
70   2024-09-01         Myntra  E-commerce  10745.0  3.072370

In [88]:
print("="*75)
print("TOP 10 ANOMALOUS TRANSACTIONS")
print("="*75)

for _, row in anomaly_report.head(10).iterrows():

    print(
        f"{row['Date'].date()}  "
        f"{row['Vendor']:<18}"
        f"{row['Category']:<20}"
        f"₹{row['Amount']:>10,.2f}  "
        f"Z={row['Z_Score']:.2f}"
    )

===========================================================================
TOP 10 ANOMALOUS TRANSACTIONS
===========================================================================
2024-05-05  Uncategorised     Others              ₹ 18,000.00  Z=3.29
2024-03-06  Uncategorised     Others              ₹ 18,000.00  Z=3.29
2024-09-01  Myntra            E-commerce          ₹ 10,745.00  Z=3.07

In [89]:
highest = anomalies.iloc[0]

print("="*70)
print("MOST UNUSUAL TRANSACTION")
print("="*70)

print("Date       :", highest["Date"].date())

print("Vendor     :", highest["Vendor"])

print("Category   :", highest["Category"])

print(f"Amount     : ₹{highest['Amount']:,.2f}")

print(f"Z-Score    : {highest['Z_Score']:.2f}")

======================================================================
MOST UNUSUAL TRANSACTION
======================================================================
Date       : 2024-05-05
Vendor     : Uncategorised
Category   : Others
Amount     : ₹18,000.00
Z-Score    : 3.29

In [90]:
category_anomalies = (
    anomalies["Category"]
    .value_counts()
)

category_anomalies

Category
Others        2
E-commerce    1
Name: count, dtype: int64

In [91]:
print("="*70)
print("ANOMALIES BY CATEGORY")
print("="*70)

max_count = category_anomalies.max()

for category, count in category_anomalies.items():

    bar = "#" * int((count/max_count)*30)

    print(f"{category:<22}{bar} ({count})")

======================================================================
ANOMALIES BY CATEGORY
======================================================================
Others                ############################## (2)
E-commerce            ############### (1)

In [92]:
top5 = anomalies.nlargest(5, "Z_Score")

top5[[
    "Vendor",
    "Category",
    "Amount",
    "Z_Score"
]]

             Vendor    Category   Amount   Z_Score
913   Uncategorised      Others  18000.0  3.291095
1128  Uncategorised      Others  18000.0  3.291095
70           Myntra  E-commerce  10745.0  3.072370

In [93]:
print("="*70)
print("ANOMALY INSIGHTS")
print("="*70)

print(f"Total Anomalies : {len(anomalies)}")

print(f"Highest Z-Score : {anomalies['Z_Score'].max():.2f}")

print(f"Average Z-Score : {anomalies['Z_Score'].mean():.2f}")

print(f"Most Affected Category : {category_anomalies.idxmax()}")

======================================================================
ANOMALY INSIGHTS
======================================================================
Total Anomalies : 3
Highest Z-Score : 3.29
Average Z-Score : 3.22
Most Affected Category : Others

In [94]:
print("="*70)
print("ANOMALY DETECTION COMPLETED")
print("="*70)

print(f"Transactions Analysed : {len(debit_df)}")

print(f"Anomalies Found       : {len(anomalies)}")

print(f"Highest Z-Score       : {anomalies['Z_Score'].max():.2f}")

print("="*70)

======================================================================
ANOMALY DETECTION COMPLETED
======================================================================
Transactions Analysed : 141
Anomalies Found       : 3
Highest Z-Score       : 3.29
======================================================================

In [95]:
# AI-assisted: Calculating spending percentages

category_amount = (
    debit_df
    .groupby("Category")["Amount"]
    .sum()
)

category_percent = (
    category_amount /
    total_debit * 100
)

category_percent

Category
Cafe                  1.185524
Cash Withdrawal       1.461205
E-commerce           17.737081
Entertainment         0.847499
Food Delivery         9.554820
Fuel                  0.529443
Groceries             2.553212
Investments          31.413959
Others               25.882324
Personal Transfer     2.644294
Quick Commerce        2.329161
Subscriptions         0.819736
Transport             2.505967
Wallet                0.535775
Name: Amount, dtype: float64

In [96]:
archetypes = []

In [97]:
food_percent = (
    category_percent.get("Food Delivery",0)
    + category_percent.get("Cafe",0)
    + category_percent.get("Restaurants",0)
)

if food_percent > 25:

    archetypes.append(
        f"🍔 THE FOODIE ({food_percent:.2f}% on food)"
    )

In [98]:
quick_percent = category_percent.get(
    "Quick Commerce",0
)

if quick_percent > 15:

    archetypes.append(
        f"🛒 THE QUICK COMMERCE JUNKIE ({quick_percent:.2f}%)"
    )

In [99]:
shopping_percent = category_percent.get(
    "E-commerce",0
)

if shopping_percent > 15:

    archetypes.append(
        f"🛍️ THE SHOPAHOLIC ({shopping_percent:.2f}%)"
    )

In [100]:
invest_percent = category_percent.get(
    "Investments",0
)

if invest_percent > 15:

    archetypes.append(
        f"📈 THE INVESTOR ({invest_percent:.2f}%)"
    )

In [101]:
if late_percentage > 50:

    archetypes.append(
        f"🌙 THE LATE-NIGHT SNACKER ({late_percentage:.2f}% after 9 PM)"
    )

In [102]:
subscription_vendors = debit_df[
    debit_df["Category"]=="Subscriptions"
]["Vendor"].nunique()

if subscription_vendors >= 5:

    archetypes.append(
        f"🎬 THE SUBSCRIPTION LOVER ({subscription_vendors} active subscriptions)"
    )

In [103]:
if savings_rate < 10:

    archetypes.append(
        f"💸 THE YOLO SPENDER (Savings Rate {savings_rate:.2f}%)"
    )

In [104]:
if savings_rate > 40:

    archetypes.append(
        f"🏦 THE DISCIPLINED SAVER ({savings_rate:.2f}%)"
    )

In [105]:
transport_percent = category_percent.get(
    "Transport",0
)

if transport_percent > 10:

    archetypes.append(
        f"🚖 THE CAB COMMUTER ({transport_percent:.2f}%)"
    )

In [106]:
coffee_shops = debit_df[
    debit_df["Category"]=="Cafe"
]["Vendor"].nunique()

if coffee_shops >= 3:

    archetypes.append(
        f"☕ THE COFFEE EXPLORER ({coffee_shops} cafe brands visited)"
    )

In [107]:
print("="*75)
print("RAHUL'S SPENDING ARCHETYPES")
print("="*75)

for item in archetypes:

    print("✅", item)

===========================================================================
RAHUL'S SPENDING ARCHETYPES
===========================================================================
✅ 🛍️ THE SHOPAHOLIC (17.74%)
✅ 📈 THE INVESTOR (31.41%)
✅ 💸 THE YOLO SPENDER (Savings Rate -20.70%)
✅ ☕ THE COFFEE EXPLORER (3 cafe brands visited)

In [108]:
print("="*70)
print("ARCHETYPE SUMMARY")
print("="*70)

print(f"Total Archetypes Detected : {len(archetypes)}")

======================================================================
ARCHETYPE SUMMARY
======================================================================
Total Archetypes Detected : 4

In [109]:
if len(archetypes)>=6:

    personality = "High Spending Lifestyle"

elif len(archetypes)>=4:

    personality = "Balanced but Impulsive"

else:

    personality = "Financially Conservative"

print("Financial Personality")

print(personality)

Financial Personality
Balanced but Impulsive

In [110]:
print("="*70)
print("PERSONALITY INSIGHTS")
print("="*70)

if "🍔 THE FOODIE" in "".join(archetypes):

    print("• Rahul spends a significant share of money on food-related purchases.")

if "📈 THE INVESTOR" in "".join(archetypes):

    print("• Despite high spending, Rahul consistently invests.")

if "💸 THE YOLO SPENDER" in "".join(archetypes):

    print("• Spending currently exceeds healthy saving levels.")

if "🌙 THE LATE-NIGHT SNACKER" in "".join(archetypes):

    print("• Most food orders occur late at night.")

======================================================================
PERSONALITY INSIGHTS
======================================================================
• Despite high spending, Rahul consistently invests.
• Spending currently exceeds healthy saving levels.

In [111]:
print("="*75)
print("SPENDING ARCHETYPE DETECTION COMPLETED")
print("="*75)

print(f"Archetypes Found : {len(archetypes)}")

for item in archetypes:

    print("-", item)

print("="*75)

===========================================================================
SPENDING ARCHETYPE DETECTION COMPLETED
===========================================================================
Archetypes Found : 4
- 🛍️ THE SHOPAHOLIC (17.74%)
- 📈 THE INVESTOR (31.41%)
- 💸 THE YOLO SPENDER (Savings Rate -20.70%)
- ☕ THE COFFEE EXPLORER (3 cafe brands visited)
===========================================================================